# NOVA ENV VARIABLES
export NOVA_USERNAME=admin
export NOVA_PASSWORD=crowbar
export NOVA_PROJECT_ID=openstack
export NOVA_API_KEY=${NOVA_PASSWORD}
export NOVA_URL=http://192.168.222.2:5000/v2.0/
export NOVA_VERSION=1.1
export NOVA_REGION_NAME=RegionOne

# COMMON ENV VARIABLES
export OS_AUTH_USER=${NOVA_USERNAME}
export OS_AUTH_KEY=${NOVA_PASSWORD}
export OS_AUTH_TENANT=${NOVA_PROJECT_ID}
export OS_AUTH_URL=${NOVA_URL}
export OS_AUTH_STRATEGY=keystone

# EUCA2OOLs ENV VARIABLES
export EC2_ACCESS_KEY=${NOVA_USERNAME}
export EC2_SECRET_KEY=${NOVA_PASSWORD}
export EC2_URL=http://192.168.222.2:8773/services/Cloud

